version: '3.8'

services:
  api:
    build: .
    container_name: user-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/users.db
      - LOG_LEVEL=INFO
      - JWT_SECRET_KEY=your-secret-key-change-in-production
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./tests:/app/tests
      - ./client:/app/client
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - user-api-network

  # Optional: Database service (for future PostgreSQL migration)
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: user-api-db
  #   environment:
  #     POSTGRES_DB: user_api
  #     POSTGRES_USER: api_user
  #     POSTGRES_PASSWORD: api_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - user-api-network

networks:
  user-api-network:
    driver: bridge

volumes:
  api_data:
    driver: local
  # postgres_data:
  #   driver: local
